name: Generate pacman animation

on:
  schedule:
    - cron: "0 * */12 * * *"   # 12 saatte bir
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Generate Pac-Man SVG(s)
        uses: abozanona/pacman-contribution-graph@main
        with:
          github_user_name: ${{ github.repository_owner }}
        # Not: Bu action varsayılan olarak light/dark üretir ve dist/ içine koyar.  :contentReference[oaicite:3]{index=3}

      - name: Publish to output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
