name: Generate pacman animation

on:
  schedule:
    - cron: "0 */12 * * *"     # 12 saatte bir, her dakikaya değil!
  workflow_dispatch:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Generate Pac-Man SVG(s)
        uses: abozanona/pacman-contribution-graph@main
        with:
          github_user_name: ${{ github.repository_owner }}

      # (İSTEĞE BAĞLI) Çıktıyı gerçekten üretti mi, gör:
      - name: Show dist contents
        run: ls -la dist

      - name: Publish to output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
